export default {
  PAGES: {
    HOME: "HOME_PAGE",
    RESTAURANT_CATEGORIES: "RESTAURANT_CATEGORIES_PAGE",
    MENU_ITEM_CATEGORIES: "MENU_ITEM_CATEGORIES_PAGE",
    FEATURED: "FEATURED_PAGE",
    RATERS: "RATERS_PAGE"
  }
}
